name: Bug Report
description: Report an issue related to the Graph Horizon upgrade
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with the Graph Horizon upgrade. Please fill out the information below to help us investigate and resolve the problem.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is experiencing the issue?
      options:
        - Indexer Agent
        - Indexer Service
        - Indexer CLI
        - TAP Agent
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your indexer setup
      value: |
        - Graph Node version:
        - Indexer Agent version:
        - Indexer Service version:
        - TAP Agent version:
        - Indexer address:
        - Operator address:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      placeholder: Paste or upload relevant logs here...
    validations:
      required: true