name: Bug Report
description: Report an issue related to the Graph Horizon upgrade
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with the Graph Horizon upgrade. Please fill out the information below to help us investigate and resolve the problem.

  - type: input
    id: indexer-address
    attributes:
      label: Indexer address
      description: The address for the indexer
    validations:
      required: true

  - type: input
    id: operator-address
    attributes:
      label: Operator address
      description: The address for the indexer's operator. Use 0x00 if not using an operator.
    validations:
      required: true

  - type: input
    id: indexer-agent-version
    attributes:
      label: Indexer agent version
      description: The indexer agent version being used - e.g: v0.25.0
    validations:
      required: true

  - type: input
    id: indexer-service-version
    attributes:
      label: Indexer service version
      description: The indexer service version being used - e.g: v1.7.0
    validations:
      required: true

      
  - type: input
    id: tap-agent-version
    attributes:
      label: TAP agent version
      description: The TAP agent version being used - e.g: v1.11.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      placeholder: Paste or upload relevant logs here...
    validations:
      required: true
